// Rooms whose descriptions are generated by routines in 1actions.zil.
// Text is verbatim from the source, assembled per world state.
import type { WorldState } from './types';
import { fset$ } from './world';

// Objects whose LDESC the original rewrites at runtime (TROLL-FCN / ROBBER-FUNCTION).
export function dynamicObjDesc(s: WorldState, obj: string): string | null {
  switch (obj) {
    case 'TROLL':
      if (s.gflags['TROLL-UNCONSCIOUS'])
        return 'An unconscious troll is sprawled on the floor. All passages out of the room are open.';
      if (s.locs['AXE'] !== 'TROLL') return 'A pathetically babbling troll is here.';
      return null;
    case 'THIEF':
      if (s.gflags['THIEF-UNCONSCIOUS'])
        return 'There is a suspicious-looking individual lying unconscious on the ground.';
      return null;
    default:
      return null;
  }
}

import { gameNumber } from '../data/games';
import { zork2RoomDesc } from './zork2/specialDescs';

export function dynamicRoomDesc(s: WorldState, room: string): string | null {
  // Each game owns its routine-generated descriptions.
  if (gameNumber() === 2) return zork2RoomDesc(s, room);

  const open = (o: string) => fset$(s, o, 'OPENBIT');
  switch (room) {
    case 'LIVING-ROOM': {
      let t = 'You are in the living room. There is a doorway to the east';
      t += s.gflags['MAGIC-FLAG']
        ? '. To the west is a cyclops-shaped opening in an old wooden door, above which is some strange gothic lettering, '
        : ', a wooden door with strange gothic lettering to the west, which appears to be nailed shut, ';
      t += 'a trophy case, ';
      const rug = s.gflags['RUG-MOVED'];
      if (rug && open('TRAP-DOOR')) t += 'and a rug lying beside an open trap door.';
      else if (rug) t += 'and a closed trap door at your feet.';
      else if (open('TRAP-DOOR')) t += 'and an open trap door at your feet.';
      else t += 'and a large oriental rug in the center of the room.';
      return t;
    }
    case 'EAST-OF-HOUSE':
      return (
        'You are behind the white house. A path leads into the forest to the east. ' +
        'In one corner of the house there is a small window which is ' +
        (open('KITCHEN-WINDOW') ? 'open.' : 'slightly ajar.')
      );
    case 'KITCHEN':
      return (
        'You are in the kitchen of the white house. A table seems to have been used recently for the preparation of food. ' +
        'A passage leads to the west and a dark staircase can be seen leading upward. ' +
        'A dark chimney leads down and to the east is a small window which is ' +
        (open('KITCHEN-WINDOW') ? 'open.' : 'slightly ajar.')
      );
    case 'RESERVOIR-SOUTH': {
      let t = 'You are in a long room on the south shore of a large lake, far too deep and wide for crossing.';
      if (s.gflags['LOW-TIDE']) {
        t =
          'You are in a long room, to the north of which was formerly a lake. However, with the water level lowered, there is merely a wide stream running through the center of the room.';
      }
      return t + ' There is a path along the stream to the east or west, a steep pathway climbing southwest along the edge of a chasm, and a path leading into a canyon to the southeast.';
    }
    case 'RESERVOIR':
      return s.gflags['LOW-TIDE']
        ? 'You are on what used to be a large lake, but which is now a large mud pile. There are "shores" to the north and south.'
        : 'You are on the lake. Beaches can be seen north and south. Upstream a small stream enters the lake through a narrow cleft in the rocks. The dam can be seen downstream.';
    case 'RESERVOIR-NORTH':
      return (
        'You are in a large cavernous room, the south of which was formerly a lake. However, with the water level lowered, there is merely a wide stream running through there.' +
        ' There is a slimy stairway leaving the room to the north.'
      );
    case 'DAM-ROOM': {
      let t =
        'You are standing on the top of the Flood Control Dam #3, which was quite a tourist attraction in times far distant. There is a path along the top of the dam to the west, and a road along the dam crest leads east.';
      t += s.gflags['LOW-TIDE']
        ? ' The water level behind the dam is low: The sluice gates have been opened. Water rushes through the dam and downstream.'
        : ' The sluice gates on the dam are closed. Behind the dam, there can be seen a wide reservoir. Water is pouring over the top of the now abandoned dam.';
      t +=
        ' There is a control panel here, on which a large metal bolt is mounted. Directly above the bolt is a small green plastic bubble' +
        (s.gflags['GATE-FLAG'] ? ' which is glowing serenely' : '') + '.';
      return t;
    }
    case 'LOUD-ROOM': {
      const quiet = s.gflags['ECHO-FLAG'];
      let t =
        'This is a large room with a ceiling which cannot be detected from the ground. There is a narrow passage from east to west and a stone stairway leading upward.';
      t += quiet
        ? ' The room is eerie in its quietness.'
        : ' The room is deafeningly loud with an undetermined rushing sound. The sound seems to reverberate from all of the walls, making it difficult even to think.';
      return t;
    }
    case 'GRATING-ROOM': {
      let t = 'You are in a small room near the maze. There are twisty passages in the immediate vicinity.';
      if (s.gflags['GRUNLOCK'] && open('GRATE'))
        t += ' Above you is an open grating with sunlight pouring in.';
      else if (s.gflags['GRUNLOCK']) t += ' Above you is a grating.';
      else t += ' Above you is a grating locked with a skull-and-crossbones lock.';
      return t;
    }
    case 'CYCLOPS-ROOM': {
      let t = 'This room has an exit on the northwest, and a staircase leading up.';
      if (s.gflags['MAGIC-FLAG'])
        t +=
          ' The east wall, previously solid, now has a cyclops-sized opening in it.';
      else if (s.gflags['CYCLOPS-FLAG'])
        t += ' The cyclops, perhaps affected by a magic spell, is sleeping blissfully at the foot of the stairs.';
      else
        t +=
          ' A cyclops, who looks prepared to eat horses (much less mere adventurers), blocks the staircase. From his state of health, and the bloodstains on the walls, you gather that he is not very friendly, though he likes people.';
      return t;
    }
    case 'TORCH-ROOM':
      return (
        'This is a large room with a prominent doorway leading to a down staircase. Above you is a large dome. ' +
        (s.gflags['DOME-FLAG'] ? 'A piece of rope descends from the railing above, ending some five feet above your head. ' : '') +
        'Up around the edge of the dome (20 feet up) is a wooden railing. In the center of the room sits a white marble pedestal.'
      );
    case 'DOME-ROOM':
      return (
        'You are at the periphery of a large dome, which forms the ceiling of another room below. Protecting you from a precipitous drop is a wooden railing which circles the dome.' +
        (s.gflags['DOME-FLAG'] ? ' Hanging down from the railing is a rope which ends about ten feet from the floor below.' : '')
      );
    case 'MAZE-5':
      return 'This is part of a maze of twisty little passages, all alike. A skeleton, probably the remains of a luckless adventurer, lies here.';
    case 'WEST-OF-HOUSE':
      return (
        'You are standing in an open field west of a white house, with a boarded front door.' +
        (s.gflags['WON-FLAG'] ? ' A secret path leads southwest into the forest.' : '')
      );
    case 'UP-A-TREE':
      return 'You are about 10 feet above the ground nestled among some large branches. The nearest branch above you is above your reach.';
    case 'GRATING-CLEARING': {
      let t = 'You are in a clearing, with a forest surrounding you on all sides. A path leads south.';
      if (open('GRATE') && s.gflags['GRATE-REVEALED']) t += '\nThere is an open grating, descending into darkness.';
      else if (s.gflags['GRATE-REVEALED']) t += '\nThere is a grating securely fastened into the ground.';
      return t;
    }
    case 'CELLAR':
      return 'You are in a dark and damp cellar with a narrow passageway leading north, and a crawlway to the south. On the west is the bottom of a steep metal ramp which is unclimbable.';
    case 'MIRROR-ROOM-1':
    case 'MIRROR-ROOM-2':
      return (
        'You are in a large square room with tall ceilings. On the south wall is an enormous mirror which fills the entire wall. There are exits on the other three sides of the room.' +
        (s.gflags['MIRROR-MUNG'] ? '\nUnfortunately, the mirror has been destroyed by your recklessness.' : '')
      );
    case 'DEEP-CANYON': {
      let t = 'You are on the south edge of a deep canyon. Passages lead off to the east, northwest and southwest. A stairway leads down.';
      if (!s.gflags['LOW-TIDE']) t += ' You can hear the sound of flowing water from below.';
      return t;
    }
    case 'ENTRANCE-TO-HADES': {
      let t =
        'You are outside a large gateway, on which is inscribed\n\n  Abandon every hope all ye who enter here!\n\nThe gate is open; through it you can see a desolation, with a pile of mangled bodies in one corner. Thousands of voices, lamenting some hideous fate, can be heard.';
      if (!s.gflags['LLD-FLAG'])
        t += '\nThe way through the gate is barred by evil spirits, who jeer at your attempts to pass.';
      return t;
    }
    case 'ARAGAIN-FALLS':
      return (
        'You are at the top of Aragain Falls, an enormous waterfall with a drop of about 450 feet. The only path here is on the north end. ' +
        (s.gflags['RAINBOW-FLAG'] ? 'A solid rainbow spans the falls.' : 'A beautiful rainbow can be seen over the falls and to the west.')
      );
    case 'BAT-ROOM':
      return 'You are in a small room which has doors only to the east and south.';
    case 'MACHINE-ROOM':
      return (
        'This is a large, cold room whose sole exit is to the north. In one corner there is a machine which is reminiscent of a clothes dryer. On its face is a switch which is labelled "START". The switch does not appear to be manipulable by any human hand (unless the fingers are about 1/16 by 1/4 inch). On the front of the machine is a large lid, which is ' +
        (open('MACHINE') ? 'open.' : 'closed.')
      );
    default:
      return null;
  }
}
